# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the desired version here
      - image: circleci/ruby:3.3.7
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      # Load installed gems from cache if possible, bundle install & clean,
      # then save cache. Multiple caches to increase the chance of a cache hit.
      # => Make sure to specify ruby version & architecture in cache keys
      #    (or conflicts on native gems may appear)
      - restore_cache:
          keys:
            - v7-gem-cache-ruby-3.3-{{ arch }}-{{ checksum "sidekiq-worker-killer.gemspec" }}-{{ checksum "Appraisals" }}
            - v7-gem-cache-ruby-3.3-{{ arch }}-

      - run:
          name: Install dependencies
          command: make bundle

      - save_cache:
          key: v7-gem-cache-ruby-3.3-{{ arch }}-{{ checksum "sidekiq-worker-killer.gemspec" }}-{{ checksum "Appraisals" }}
          paths:
            - .bundle

      # Run tests!
      - run:
          name: Run tests
          command: make test
